### ISSUE TITLE
Incorrect output format in package `detect-is-it-html-or-xhtml`

### ISSUE THREAD

**Issue by mohit-mavq** [codsen/codsen#10]
**Package's name**
detect-is-it-html-or-xhtml

**Describe the bug**
Not providing the correct format on various cases

**To Reproduce**
Input -> `<p>Hello</p>`
Expected -> 'html' / 'xhtml'
Actual -> null

**Comment by revelt** [comment]
hi Mohit! Thank you for considering this package!

It seems it's not a bug. I described the algorithm in [readme](https://codsen.com/os/detect-is-it-html-or-xhtml/#under-the-hood):

> 4. If (there are no tags in the input) OR (there are no doctype tags and no singleton tags), return null.

So, `<p>...</p>` could be either HTML or XHTML, hence program returns `null`. Type can't be identified.

So you see? We need singleton tags or a doctype to be present.

**Comment by mohit-mavq** [comment]
So, <p>...</p> could be either HTML or XHTML, hence program returns null. Type can't be identified.

Can we enhance this to provide an array saying that it could be a valid HTML/XHTML instead of passing null and Null in only cases where we know it's none of any?

**Comment by revelt** [comment]
In theory, yes. 

It feels like what you seek, could be another package, a wrapper of this-one. Imagine, that new program takes a string, runs quickly past this program, then if `null` is still returned, does the validation part, checks let's say, for raw bracket presence etc. 

The dilemma is, **how strictly do you check** the presence of tags. It can be anything from `/<\w/g` to try-catch around a lexer/parser and looking for `token.type === "tag"`... If there are security requirements, you'd want to kill any insecure characters, definitely no `a<b` is allowed in that case, even this `a<b` is a partial tag and must be stripped or whatever. But If requirements are lax, if plausible cases can exist, like `detergent.io` is processing text, `a<b` is probably not a tag. Also, speed is a consideration.

Do you see?

To me it feels a wrapper package with extra checks (tailored to your strictness requirements) would be more reasonable...
