### ISSUE TITLE
Stripped tags get replaced with spaces

### ISSUE THREAD

**Issue by jonathanstokes** [codsen/codsen#13]
**Package's name**
`string-strip-html`

**Describe the bug**
When a tag is used surrounded by characters, i.e. within a word, the output has spaces introduced where tags were present.

**To Reproduce**

The following fails:
```JavaScript
import { strict as assert } from "assert";
import { stripHtml } from "string-strip-html";

assert.equal(
  stripHtml('This has an <b>un</b>bold word.').result
  'This has an unbold word.'
);
```

Instead, it resolves to `'This has an un bold word.'`.

**Expected behavior**
Tags should not result in extra spaces, so `stripHtml('i<u>am</u>groot').result` should be `'iamgroot'` when stripped.

**Comment by revelt** [comment]
hi Jonathan! Sorry about that, I checked, yes, it does happen. I'll try to fix.

**Comment by revelt** [comment]
in the meantime, you can override the algorithm using `opts.cb`:

```js
// Just deletes inline tags

import { strict as assert } from "assert";
import { stripHtml } from "../dist/string-strip-html.esm.js";

const someHtml = `This has an <b>un</b>bold word.`;

// default behaviour:
assert.equal(stripHtml(someHtml).result, `This has an un bold word.`);

// let's tackle inline tags:
assert.equal(
  stripHtml(someHtml, {
    cb: ({ tag, deleteFrom, deleteTo, insert, rangesArr }) => {
      console.log(
        `tag: ${JSON.stringify(
          tag,
          null,
          4
        )}`
      );
      if (["b", "strong"].includes(tag.name)) {
        rangesArr.push(tag.lastOpeningBracketAt, tag.lastClosingBracketAt + 1);
      } else {
        rangesArr.push(deleteFrom, deleteTo, insert);
      }
    },
  }).result,
  `This has an unbold word.`
);
```

I'll try to implement the inline tag recognition out-of-the-box, on default settings.

**Comment by revelt** [comment]
This has been fixed since, I'll close, but feel free to reopen or create a new ticket.

**Comment by lublak** [comment]
@revelt i have the same issue but with longer tags
```
<body>test</body>123
```
to:
```
test 123
```
