### ISSUE TITLE
Strategy for use with streams/gulp?

### ISSUE THREAD

**Issue by rootwork** [codsen/codsen#14]
**Package's name**
detergent, others

**Describe the situation**
You have a fantastic set of email-related packages that I'd really like to use. Currently, all my email-code-creation is done within the context of Gulp (4) tasks. It seems like most of your packages expect data to be passed in as strings, like operating on a particular file, but I primarily deal with data coming in as part of Node streams. When I try to integrate any of your packages into my Gulp builds, I inevitably get an error like "argument must be of a string type, not object." (I would think a Node stream's chunk would be a string, not an object, but maybe I'm wrong.)

I tried both the usual `.pipe()` method as well as going the [vinyl-transform](https://www.npmjs.com/package/vinyl-transform) route.

Do you use your packages as part of streams or build processes? If so, do you have any recommendations or recipes on how best to do it?

Thanks!

**Comment by revelt** [comment]
hi Ivan! Try `gulp-tap`, like in this example: https://codsen.com/os/email-comb/#tapping-the-stream-in-gulp

The idea is, you convert stream to string using `file.contents.toString()`, then assign modified string to `file.contents` (don't return it, it's passed as a reference, so just mutate it by assigning a new value), like: `file.contents = Buffer.from(cleanedHtmlResult.result);`

I like streams but people generally don't, for example compare two tag stripping programs: https://npmcharts.com/compare/string-strip-html,strip-html?interval=30 — I admit there are benefits from streams (memory usage etc) but this conversion to string and back doesn't have much of an impact in daily ops from my experience. Imho, the real impact would be from _better tooling_, imagine a compiled, universal, all-in-one processing by a program written in Rust or Go, like esbuild, how cool would be that!

Anyway, let me know how it goes.

**Comment by rootwork** [comment]
Excellent, this was very helpful. I got the `string-remove-widows` package working with this method.

Now I'm excited to try out all of your packages :)

I really appreciate the help! And I agree with you, better tooling would be nice!
