### ISSUE TITLE
False positive tag detection to "a<b and c>d" resulting to  "a d"

### ISSUE THREAD

**Issue by guillermodiazga** [codsen/codsen#18]
**Package's name**
stripHtml

**Describe the bug**

**To Reproduce**
False positive tag detection to "a<b and c>d" resulting to  "a d"

Also if you try using "a<b" the result is wrong "a"

**Expected behavior**
When there's  only '<' should preserved the content

**Comment by revelt** [comment]
hi! Thank you for raising this. Since original inception the algorithm got more and more complex, in the end we chose to go belt-and-braces and strip tags more aggressively because un-encoded brackets should be flagged up by linters anyway. I've removed references to this old example from readme.

**Comment by mherger** [comment]
Would stripping the `<b` from `H4<bE77]7oQL` fall into the same category?

**Comment by revelt** [comment]
@mherger hm, not really. Thank you for reporting, I created https://github.com/codsen/codsen/issues/20 for that.
