### ISSUE TITLE
string-extract-class-names with Typescript

### ISSUE THREAD

**Issue by tcastelly** [codsen/codsen#21]
Hello,

**string-extract-class-names**
Since the the version 7.x.x the import of the module has been changed. It seams that we have to use it in a .mjs file. Or add `"type": "module"` to the package.json file.
The problem is with Typescript , no solution works. How is possible to use it?

Thank you very much for any help.

**Comment by revelt** [comment]
hi @tcastelly. If your nearest package.json is not `type: "module"` yet, just use legacy version `6.1.0`. Unless it's something else, in which case please post screenshots of the error. Basically, if it's ESM thing, there's nothing you can do besides either using legacy version or moving to ESM. However, if there's something bunged up with TS side (Rollup plugins did something not right) then it's something more serious.

**Comment by tcastelly** [comment]
Thank you for your answer.
My "solution" to ba able to use string-extract-class-names with TS in NodeJS environment, is to rename to .mjs and add `// @ts-check` to the file.

**Comment by revelt** [comment]
OK, so it was just ESM thing, phew. Have a great day!
