### ISSUE TITLE
C\C++ header tags in html gets removed

### ISSUE THREAD

**Issue by OfirD1** [codsen/codsen#23]
**Package's name**
`string-strip-html`

**Describe the bug**
Not sure if this is by design or a bug, but C\C++ `#include <header.h>` code in HTML gets removed.

**To Reproduce**

Run:
```javascript
import { stripHtml } from 'string-strip-html';

console.log(stripHtml('<code>#include <stdio.h>;<code>').result);
console.log(stripHtml('<code>#include &lt;stdio.h&gt;</code>').result);
```

Output:
```bash
#include;
#include
```

**Expected behavior**
Non-Html tags shouldn't be removed, so the output should be:
```bash
#include <stdio.h>;
#include <stdio.h>;
```

**Live Demo**
https://stackblitz.com/edit/node-jmbga3?file=index.js

**Additional context**
Faced that problem when tried to parse questions content from StackOverflow.

**Comment by revelt** [comment]
Sorry about the trouble! The current algorithm is quite eager, I supply an "escape latch" via `opts.cb()` but it's manual and tedious. In current situation, I'm thinking a new options flag would help, a toggle to force the algorithm to strip only the recognised HTML: sequence `<` optionally followed by slash, followed tag name, followed by closing bracket or whitespace. In this case, `<stdio.h>` as unrecognised HTML would not be stripped! Option could be named like `opts.stripRecognisedHTMLOnly` for example. What do you think?

**Comment by OfirD1** [comment]
The option `opts.stripRecognisedHTMLOnly` is good. 

In addition, consider also a case where one has a `<code>` block with nested HTML tags. There are use-cases where it is desired to keep element nested under the `<code>` blocked completely unremoved.  
One such use-case is ~~scraping~~ using API to get content from sites like StackOverflow (similar to my use-case above), where questions contain code blocks that should be kept intact.  

So maybe a more sophisticated option `opts.ignoreUnderQuerySelector` should be provided, where the user supplies a query selector (e.g., `code`, `.code`, or `#code`) and then the engine ignores nested content under matched elements.

**Comment by revelt** [comment]
Sorry for delay, I'll jump on this feature next.

**Comment by revelt** [comment]
Looking at this particular case, it seems that the most exact feature requirement would be a new `opts.ignoreTagsWithTheirContents`, — opposite of existing `opts. stripTogetherWithTheirContents`

**Comment by revelt** [comment]
released in v.9.1.0:

```js
// Ignores code tags and their contents

import { strict as assert } from "assert";
import { stripHtml } from "string-strip-html";

const someHtml = `<code>#include <stdio.h>;</code> and <code>#include &lt;stdio.h&gt;</code>`;

// default behaviour:
assert.equal(stripHtml(someHtml).result, `#include; and #include`);

// ignore <code> tag pairs
assert.equal(
  stripHtml(someHtml, {
    ignoreTagsWithTheirContents: ["code"],
    skipHtmlDecoding: true,
  }).result,
  someHtml
);
```
