### ISSUE TITLE
string-strip-html can not be used from React Native

### ISSUE THREAD

**Issue by mi5ha** [codsen/codsen#24]
**Package's name**
string-strip-html

**Describe the bug**
Metro bundler complains that main file is not set correctly in package.json.

**Solution**
Just adding this to package.json solves an issue:

```
"module": "dist/string-strip-html.esm.js",
```

**Comment by revelt** [comment]
linking the original `metro` ticket https://github.com/facebook/metro/issues/670https://github.com/facebook/metro/issues/670

**Comment by mi5ha** [comment]
@revelt  Cant string-strip-html support both?

**Comment by revelt** [comment]
I can easily restore the `module` entry in `package.json`s but my main concern is that it's not conforming to the ESM spec — specifically, I'm worried about [dual package hazard](https://nodejs.org/api/packages.html#packages_dual_package_hazard). Until metro is issue no.670 is fixed, would it be feasible not to bump `string-strip-html` and stay with `v8.3.0`?

**Comment by mi5ha** [comment]
Sounds like a solution 😃 thanx!

**Comment by revelt** [comment]
Thank you. Sorry about the situation.
