### ISSUE TITLE
attribute-required is showing up when it shouldn't

### ISSUE THREAD

**Issue by avigoldman** [codsen/codsen#30]
**Package's name**
emlint

**Describe the bug**
The linter is reporting a missing href attribute on the closing `</a>` 

**To Reproduce**

Run the following JS code:
```js
import {Linter} = from 'emlint'

const linter = new Linter()

linter.verify(`<a href="/test">hello world</a>`, {rules: {
  'attribute-required': [
    1,
    {
      a: {
        href: true,
      },
    },
  ],
}})
```

It returns the following: 
```json
[
  {
    "fix": null,
    "keepSeparateWhenFixing": false,
    "line": 1,
    "column": 28,
    "severity": 1,
    "ruleId": "attribute-required",
    "message": "Attribute \"href\" is missing.",
    "idxFrom": 27,
    "idxTo": 31
  }
]
```

**Expected behavior**
I'd expect this code to come back as completely valid as an empty array.

**Screenshots**
N/A

**Comment by revelt** [comment]
Sorry, it's the work-in-progress program; I'm closing this ticket.
