### ISSUE TITLE
allow self-closing tags to contain a trailing space

### ISSUE THREAD

**Issue by avigoldman** [codsen/codsen#32]
**Package's name**
emlint

**Describe the bug**
The linter is reporting that the self closing tag should not contain a trailing space

**To Reproduce**

Run the following JS code:
```js
import {Linter} = from 'emlint'

const linter = new Linter()

linter.verify(`<br />`, {rules: {
  'tag-space-before-closing-bracket': 2,
}})
```

It returns the following: 
```json
[
  {
    "fix": {
      "ranges": [
        [
          3,
          4
        ]
      ]
    },
    "keepSeparateWhenFixing": false,
    "line": 1,
    "column": 1,
    "severity": 2,
    "ruleId": "tag-space-before-closing-bracket",
    "message": "Remove space.",
    "idxFrom": 0,
    "idxTo": 6
  }
]
```

**Expected behavior**
I'd expect this code to come back as completely valid as an empty array.

**Screenshots**
N/A

**Comment by revelt** [comment]
Sorry, it's the work-in-progress program; I'm closing this ticket.
