### ISSUE TITLE
email-comb hangs on large html

### ISSUE THREAD

**Issue by luddd3** [codsen/codsen#35]
**Package's name**
email-comb

**Describe the bug**
I have an email which causes email-comb to hang indefinitely. More specific, it is this line that causes it to hang:
https://github.com/codsen/codsen/blob/8b2aebe2dadb78bbef01ac9ed1305955b35f368c/packages/email-comb/src/main.ts#L4106

**To Reproduce**
1. Run email-comb with this input (8MB html extracted from an email) Note that the file will disappear after 7 days. I can send it to someone directly if they want to take a look.
https://send.vis.ee/download/dd094bfe3bdadb8a/#6brAyO9Zv9_0TUCrgbR_RA

I realize that the email is quite large, but maybe someone can think of a quick fix to make the regexp more performant.

**Comment by luddd3** [comment]
Hi,

I'm using the email-comb npm package. I've been using it for a long time to process emails that I receive, probably thousands of different emails. This is the first time I've had an issue. Unfortunately I cannot use any online-tools to preprocess them.

When I'm stepping through the code with a debugger, everything works just fine and quite fast until I hit that regex for the empty media queries. If it is impossible/difficult to find another regexp, then maybe a flag to whitelist or skip empty media query removal would be possible? The best would of course be to find an alternative regexp or another way.

**Comment by revelt** [comment]
OK, I'll have a look.

**Comment by revelt** [comment]
I think I have a fix, patch is releasing now. I built 8MB file with 20K tags each having unused CSS, test ended taking around 20s:

![Screenshot 2022-01-11 at 21 38 16](https://user-images.githubusercontent.com/8344688/149030135-04fb3859-973e-499c-af23-56b7bbb5073f.png)

Your original file only had around 10 unused classes/id's only, so it should take around a second after fix.

It's releasing, but feel free to reopen if it doesn't work.

**Comment by revelt** [comment]
published! try the latest https://www.npmjs.com/package/email-comb/v/6.1.8

**Comment by luddd3** [comment]
Thank you! =)
