### ISSUE TITLE
lerna-clean-changelogs-cli: --extras flag cannot be turned off

### ISSUE THREAD

**Issue by drewbrend** [codsen/codsen#36]
**Package's name**
lerna-clean-changelogs-cli

**Describe the bug**
`--extras` is a flag that is a flag that removes links from the version numbers in changelogs.  That is designed to be off by default but is always happening, regardless of whether the `--extras` flag is provided or how it is used.

**To Reproduce**

1. run `lernacleanchangelog '**'` is a project with a CHANGELOG that have links in their versions, like:
`## [2.9.0](https://gitlab.com/codsen/codsen/tree/master/packages/ranges-apply/compare/ranges-apply@2.8.1...ranges-apply@2.9.0) (2018-12-26)`
2. Notice the outputted CHANGELOG has the version link removed:
`## 2.9.0 (2018-12-26)`

**Expected behavior**
Version links should not be modified:
`## [2.9.0](https://gitlab.com/codsen/codsen/tree/master/packages/ranges-apply/compare/ranges-apply@2.8.1...ranges-apply@2.9.0) (2018-12-26)`

**Additional context**
This is happening because the CLI is calling the underlying library incorrectly.  It's providing `extras` [as a property of an object](https://github.com/codsen/codsen/blob/main/packages/lerna-clean-changelogs-cli/cli.js#L75-L77), where the library [expects a simple boolean](https://github.com/codsen/codsen/blob/main/packages/lerna-clean-changelogs/src/main.ts#L13).

PR for the fix is here: #37

**Comment by revelt** [comment]
should be fixed in latest release:
- lerna-clean-changelogs-cli 2.0.12
- lerna-clean-changelogs 4.0.0
