### ISSUE TITLE
Strange error with Node16.13.2

### ISSUE THREAD

**Issue by okolawol** [codsen/codsen#41]
**Package's name**
string-strip-html @ 9.1.6

 

**Describe the bug**
On my node 16.13.2 typescript project, when I try to import the package, an ERR_REQUIRE_ESM shows up and asks to change 'require' to 'import'. The issue is there is no require statement used anywhere in my typescript project

**To Reproduce**
1. with node 16.13.2 / npm 8.1.2 install string-strip-html @ 9.1.6

2. import { stripHtml } from "string-strip-html"

3. try to compile the project with ts-node index.ts

4. see error
<img width="1105" alt="Screen Shot 2022-02-18 at 9 47 40 AM" src="https://user-images.githubusercontent.com/3300105/154735814-840d42ce-fe05-4e4e-8cdf-56fb7ba3a3bd.png">
<img width="646" alt="Screen Shot 2022-02-18 at 9 48 28 AM" src="https://user-images.githubusercontent.com/3300105/154735884-dcec3984-5a73-4003-91a2-b46607f4238d.png">
<img width="414" alt="Screen Shot 2022-02-18 at 9 47 13 AM" src="https://user-images.githubusercontent.com/3300105/154735969-f7713a70-3efa-4c4f-8142-51dfcbe92448.png">
<img width="393" alt="Screen Shot 2022-02-18 at 9 48 05 AM" src="https://user-images.githubusercontent.com/3300105/154735997-e9186262-f33d-4557-899a-2b44aed8c07c.png">

 

**Expected behavior**
The module should be imported

 

**Additional context**
I switched to an older version and it worked fine.

**Comment by revelt** [comment]
hi @okolawol ! Sorry about the problem. `ts-node` is not up-to-speed with ESM, see https://github.com/TypeStrong/ts-node/issues/1007 . I've been using it myself in CLI checker scripts and I can confirm it fails on ESM projects while working fine on non-esm. It's not a problem of this package, it's a general problem, you'll encounter the same with any other ESM package...

I'll close this issue; we can't do much about that. Personally, I started looking into deno for TS-native scripting... It's very frustrating.
