### ISSUE TITLE
edit-package-json incompatibility with typescript 4.7.3, moduleResolution Node16

### ISSUE THREAD

**Issue by paulzacz** [codsen/codsen#47]
**Package's name**
Which package from the monorepo is it for?

edit-package-json

**Describe the bug**

Typescript cannot find the types for ``edit-package-json`` when using "moduleResolution": "Node16", on typescript v4.7.3

**To Reproduce**

tsconfig.json
```
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "Node16",
  }
}
```
Sample file:
```
import { del, set } from 'edit-package-json';
```
Error message:
```
error TS7016: Could not find a declaration file for module 'edit-package-json'. 'node_modules/edit-package-json/dist/edit-package-json.esm.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/edit-package-json` if it exists or add a new declaration (.d.ts) file containing `declare module 'edit-package-json';`

import { del, set } from 'edit-package-json';
```

**Expected behavior**
Typescript is able to find the type definitions.

**Additional context**
Typescript 4.7.3 added support for ESM modules in node.js, including the "exports" keyword in package.json. The relevant portion of package.json for edit-package-json is as follows:
```
  "exports": {
    "script": "./dist/edit-package-json.umd.js",
    "default": "./dist/edit-package-json.esm.js"
  },
  "types": "types/index.d.ts",
```
As written, Typescript 4.7.3 is looking for ``./dist/edit-package-json.esm.d.ts``, but that files does not exist. Either add a "types" within the "exports" section pointing to the right file, or change the build process to output a definition file in the expected location with the expected name. [Typescript 4.7.3 exports reference](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing)

**Comment by revelt** [comment]
Interesting, it's happening on other libs too: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#comment-328

**Comment by revelt** [comment]
I recreated the setup with the aforementioned `compilerOptions` and TS `4.7.4`:

- StackBlitz: https://stackblitz.com/edit/typescript-qbdjcy?file=index.ts
- npm package style, reproduction repo on GH: https://github.com/revelt/repro

TS transpiles fine using `tsc`! It's not enough to just put those `compilerOptions` and TS `4.7.4`.

Please choose and fork one of the above and adapt to your breaking code, trimming it down until you are able to distill the **minimal proof case**.

Also, with regards to the type definitions being in the different folder — `redux` uses [exactly the same path style](https://github.com/reduxjs/redux/blob/9b45aa946be3860ca41ca05ab991947b2f7d0914/package.json#L29) `"types": "types/index.d.ts",`. That's a common pattern.

I'll close this issue now but when you have an MVP proof, re-open.

**Comment by paulzacz** [comment]
> Also, with regards to the type definitions being in the different folder — redux uses [exactly the same path style](https://github.com/reduxjs/redux/blob/9b45aa946be3860ca41ca05ab991947b2f7d0914/package.json#L29) "types": "types/index.d.ts",. That's a common pattern.

Yes, that's a common pattern, but a deprecated pattern. The major feature of Typescript 4.7.3 was first-class support for Node16 modules. Previously, Typescript didn't know about package.json exports, now it does so long as you have the correct tsconfig settings to enable it. Once it starts paying attention to "exports", it ignores the top-level "main" and "types.

**Comment by revelt** [comment]
Thank you! Reopening.

**Comment by revelt** [comment]
Fixed in v0.6.5 patch, I checked the reproduction repo, types load fine. Closing. Thank you for all the help!

**Comment by paulzacz** [comment]
Thank you as well. I had no idea you auto-generated your own package.json files so extensively. Also, I didn't know that JavaScript preserved the order of its object keys internally. I just assumed they were unordered hash maps under the hood.

**Comment by paulzacz** [comment]
Wow, thanks for the quick reply. Being able to add new keys or set the
DEBUG flag would also be nice, but are more work.
