### ISSUE TITLE
no whitespace between quotation marks and tags

### ISSUE THREAD

**Issue by peterbe** [codsen/codsen#49]
**Package's name**
Which package from the monorepo is it for? 
`string-strip-html`

**Describe the bug**

```js
import { stripHtml } from "string-strip-html";

const html = `<ul>
<li>"<a href="/Foo/bar">Foo Bar</a>"</li>
<li>(<strong>Strong</strong>)</li>
</ul>`
console.log(stripHtml(html).result)
```
Output becomes:
```
" Foo Bar"
( Strong)
```

**To Reproduce**

https://glitch.com/edit/#!/glib-west-prawn?path=server.js%3A1%3A0

**Expected behavior**

Instead of the output mentioned above, I'd expect
```
"Foo Bar"
(Strong)
```
Note the removed whitespace after the first `"` or `(`.

**Additional context**

I'm trying to improve our current code that turns HTML into plain text from a Cheerio object.

**Comment by peterbe** [comment]
Hmm. Perhaps I'm not understanding how to use this. 
```html
<p>foo<b>bar</b></p>
```
becomes:
```
foo bar
```

but when viewed as HTML it will appear as: **foo**bar

**Comment by revelt** [comment]
hi Peter, sorry for the bug, I've just fixed the brackets and quotes cases you mentioned on the first post. What's left is the second example, the `foo bar`.

**Comment by revelt** [comment]
Hi Peter! v11 just released with inline tag recognition, it tackles the `<p>foo<b>bar</b></p>`. Thank you for raising this; it was on my to-do list for too long. Please report any inconsistencies you find. Have a great rest of the weekend!

**Comment by peterbe** [comment]
I just tested. 

```js
const html = `
<div>

<ul>
<li>"<a href="/Foo/bar">Foo Bar</a>"</li>
<li>(<strong>Strong</strong>)</li>
</ul>

<p>foo<b>bar</b></p>
<p>Hi John! How are you?</p>

<p>new email address and click <strong>Add</strong>.</p>
</div>`
console.log(stripHtml(html).result)
```
becomes...
```
"Foo Bar"
(Strong)
foobar
Hi John! How are you?
new email address and click Add.
```
which I would say is perfect. It's what I'd see (and mouse-select-and-copy) in a web browser from that HTML.
