### ISSUE TITLE
lerna-clean-changelog does not work on windows host

### ISSUE THREAD

**Issue by heilmela** [codsen/codsen#50]
**Package's name**
lerna-clean-changelogs

**Describe the bug**
Im using this package in my CI build process to generate release notes with a bit less noise.
One of my projects is built on a windows host and the clean changelog function without any options is just a noop and returns the file content.

**To Reproduce**

1. Be on windows
2. Read in Changelog.md file with only bump messages
4. Clean changelog wont have any effect

**Expected behavior**
Should work on windows 

**Additional context**
In my case I just replace windows new line style `\n\r` with `\n` resolves the issue. 
The problem resides on line 47: `(!changelog.includes("\n") || !changelog.includes("\r"))`
Which causes the function to exit early on windows.

**Comment by revelt** [comment]
hi Laurin, sorry about the bug! I'll patch it asap.

**Comment by revelt** [comment]
hi Laurin, I've just patched and released 4.2.2 please try it.

**Comment by revelt** [comment]
I'll close the ticket but feel free to reopen is bug hasn't been solved.
