### ISSUE TITLE
is-language-code: Memory leak

### ISSUE THREAD

**Issue by andrucz** [codsen/codsen#52]
**Package's name**
is-language-code

**Describe the bug**
I detected a memory leak after thousands of calls to `isLangCode`. It seems it adds regular expressions to global arrays: https://github.com/codsen/codsen/blob/13de072632c06347f82a141e0a7e0c5fc108d428/packages/is-language-code/src/main.ts#L72

**To Reproduce**
Create a loop to call `isLangCode` thousands of times and verify the memory usage.

**Expected behavior**
Calls to `isLangCode` shouldn't affect memory usage.

**Screenshots**

**Additional context**

**Comment by revelt** [comment]
Hi! Sorry about the bug, I'll try to fix it.

**Comment by revelt** [comment]
I've just released a patch, `4.1.2`, please try. I moved the state-tracking arrays inside the main function and wiped each array before each main function's return.

**Comment by andrucz** [comment]
@revelt thanks for the prompt response. That does the trick!

**Comment by revelt** [comment]
Thank you!
