### ISSUE TITLE
eslint error => "string-strip-html" is not found

### ISSUE THREAD

**Issue by yim-jj** [codsen/codsen#53]
**Package's name**
string-strip-html
version: 11.6.4

**Describe the bug**
Found the following error after running eslint.
Error message: "string-strip-html" is not found

**To Reproduce**
1. After declaring the following in the react component:
import { stripHtml } from "string-strip-html";

2. Run eslint command
eslint . --ext .js,.jsx,.ts,.tsx

**Expected behavior**
No error occurs after running eslint.

**Additional context**

Installed Packages:
typescript@4.8.2
eslint-config-airbnb-typescript@17.0.0
eslint-config-airbnb@19.0.4
eslint-config-next@12.2.5
eslint-config-prettier@8.5.0
eslint-plugin-jsx-a11y@6.6.1
eslint-plugin-node@11.1.0
eslint-plugin-storybook@0.6.4
eslint@8.23.0

.eslintrc.json

{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "extends": [
    "next/core-web-vitals",
    "prettier",
    "airbnb-typescript",
    "plugin:node/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:storybook/recommended"
  ],
  "parserOptions": {
    "tsconfigRootDir": "./",
    "project": "./tsconfig.json"
  },
  "rules": {
    "quotes": "off",
    "@typescript-eslint/quotes": ["error", "double"],
    "node/no-unsupported-features/es-syntax": "off",
    "node/no-deprecated-api": [
      "error",
      {
        "ignoreModuleItems": ["url.parse"]
      }
    ],
    "node/no-missing-import": [
      "error",
      {
        "tryExtensions": [".js", ".json", ".node", ".ts", ".tsx"]
      }
    ],
    "comma-dangle": "off",
    "@typescript-eslint/comma-dangle": ["error", "only-multiline"],
    "indent": "off",
    "@typescript-eslint/indent": "off",
    "jsx-a11y/alt-text": "off",
    "@typescript-eslint/no-unsafe-return": "off"
  }
}

**Comment by revelt** [comment]
hi! Sorry about that. Let's try few things. First, double-check, is the `string-strip-html` installed — run `npm i` again. Second, run `npm ls string-strip-html` — it will pick up what's currently installed, across the deps tree. Then, let's look what exactly is eslint complaining about. If possible, post the terminal message here, there might be clues. If you're on Mac, cover all sensitive bits using Preview editor or Photoshop. Basically, I'm interested, does eslint report the main import line or something else.

Please post here how it goes.

**Comment by yim-jj** [comment]
Hi!
Same problem again. Here is screenshot as your comment.

<img width="1792" alt="스크린샷 2022-09-15 오후 12 55 06" src="https://user-images.githubusercontent.com/76460116/190310389-55016bae-a5f7-452e-a9cd-5cfc3ea319c0.png">

**Comment by yim-jj** [comment]
I added the following (Bold/Italic text) to .eslintrc.json and the error went away, but I don't know why I need to add it.

"node/no-missing-import": [
      "error",
      {
        **_"allowModules": ["string-strip-html"],_**
        "tryExtensions": [".js", ".json", ".node", ".ts", ".tsx"]
      }
    ],

**Comment by revelt** [comment]
This package is pure-ESM, and this lint rule doesn't support ESM — https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-missing-import.md says "ECMAScript 2015 (ES6) does not define the lookup logic and Node does not support modules yet."

Interestingly, the Remix lint config does not use this rule: https://github.com/remix-run/remix/blob/main/packages/remix-eslint-config/internal.js it uses only order and consistency import rules.

I'd say it's fine to ignore like you're doing, as long as it works. If string-strip-html doesn't work, use last pre-ESM version 8.3.0.

**Comment by revelt** [comment]
I'll close but feel free to reopen or open a new ticket. Have a great day!
