### ISSUE TITLE
error  Unable to resolve path to module 'string-strip-html'  import/no-unresolved

### ISSUE THREAD

**Issue by numbing** [codsen/codsen#58]
**string-strip-html**

**Describe the bug**
using eslint i am getting this error only on this package "error  Unable to resolve path to module 'string-strip-html'  import/no-unresolved"

**To Reproduce**
following is my eslint extends, and when i use eslint seems like it cant find path
  extends: [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:import/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:@typescript-eslint/recommended",
    "eslint-config-prettier",
  ],

**Comment by revelt** [comment]
hi! Please try:

1. delete node_modules and if possible, the lockfile (yarn or npm, whichever you use)
2. `npm i` or `yarn`
3. close and open the VSCode

does it still persist?

**Comment by numbing** [comment]
Hi, thank you for your response. i just made it works by adding this to the .eslintrc
parserOptions: {
    requireConfigFile: false,
    babelOptions: {
      babelrc: false,
      configFile: false,
      presets: ["@babel/preset-env"],
    },
  },

**Comment by revelt** [comment]
great! closing
