### ISSUE TITLE
[color-shorthand-hex-to-six-digit] Accept strings with no hash

### ISSUE THREAD

**Issue by blakegearin** [codsen/codsen#59]
**Package's name**
[`color-shorthand-hex-to-six-digit`](https://github.com/codsen/codsen/tree/main/packages/color-shorthand-hex-to-six-digit)

**Is your feature request related to a problem? Please describe.**
`conv` accepts `#ccc` but not `ccc` even though it's a reasonably valid representation of a hex color code. 

**Describe the solution you'd like**

Original: 
https://github.com/codsen/codsen/blob/main/packages/color-shorthand-hex-to-six-digit/src/main.ts#L29-L38

Proposed: 
```ts
// consider false positives like &#124;
if (string[offset - 1] !== "&") {
  startIndex?: number = null;

  if (hex.length === 4 && hex.charAt(0) === "#") startIndex = 1;
  if (hex.length === 3 && hex.charAt(0) !== "#") startIndex = 0;

  if (startIndex) {
    return `#${hex.charAt(startIndex)}${hex.charAt(startIndex)}${hex.charAt(startIndex+1)}${hex.charAt(startIndex+1)}${hex.charAt(startIndex+2)}${hex.charAt(startIndex+2)}`.toLowerCase();
  }
}
return hex.toLowerCase();
```

**Describe alternatives you've considered**
Accepting this string format could be put behind a flag.

**Additional context**
I don't have too much experience with TS. Please double check my syntax.

**Comment by revelt** [comment]
hi Blake,
Thanks for the suggestion. The main purpose of `color-shorthand-hex-to-six-digit` is to process any data structures (strings, arrays, plain objects), reliably and without a config. I'm a bit reluctant to introduce an Options object. If the input has no hash, there is a huge risk of false positives, for example, `cab` is a valid hex colour. Would you like to write a new, specialised library which does the replacing? At it's most basic variation, if you have an extracted 3-character string without a hash, you can just use regex:

```js
const str = "cab";
console.log(str.replace(/(\w)(\w)(\w)/g, "$1$1$2$2$3$3"))
// => ccaabb
```
