### ISSUE TITLE
edge-cases when "combing" strings containing template delimiters

### ISSUE THREAD

**Issue by romain20100** [codsen/codsen#6]
**Package's name**
email-comb

**Describe the situation**
So, the way to reproduce this issue is quite finicky, but is still a real world example and therefore I think this should be investigated.

For this issue I think giving examples of what breaks and what works will help more. Of course, keep in mind the following snippets are simplified for the purpose of staying readable and to emphasize where the problem probably comes from. This actually happens on real world code, and you'll see why below:

Here is a first (control) example that works as intended

**Input**

```html
<style>
@font-face {
  font-family: 'SomeFont';
  font-style: normal;
  font-weight: 400;
  src: url({{ static_url }}/some-path.ttf) format('truetype');
}
</style>
```

---

Here is a first example that breaks

**Input**

```html
<style>
@font-face {
  font-family: 'SomeFont';
  font-style: normal;
  font-weight: 400;
  src: url({{ static_url }}/some-path.ttf) format('truetype');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
</style>
```

**Output**

```html
<style>
@font-face {
  font-family: 'SomeFont';
  font-style: normal;
  font-weight: 400;
  src: url({{ static_url }}U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
</style>
```

---

However, if you treat the css directly (no opening style tag), then it works

**Input**

```css
@font-face {
  font-family: 'SomeFont';
  font-style: normal;
  font-weight: 400;
  src: url({{ static_url }}/some-path.ttf) format('truetype');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
```

Or if you put the unicode-range attribute before the template variable, it works too

**Input**

```html
<style>
@font-face {
  font-family: 'SomeFont';
  font-style: normal;
  font-weight: 400;
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  src: url({{ static_url }}/some-path.ttf) format('truetype');
}
</style>
```

---

Here is another example that breaks

**Input**

```html
<style>
@font-face {
  font-family: '{{ font_name }}';
  font-style: normal;
  font-weight: 400;
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  src: url({{ static_url }}/some-path.ttf) format('truetype');
}
@font-face {
  font-family: '{{ font_name }}';
  font-style: normal;
  font-weight: 400;
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  src: url({{ static_url }}/some-path.ttf) format('truetype');
}
</style>
```

**Output**

```html
<style>
@font-face {
  font-family: '{{ font_name }}';
  font-style: normal;
  font-weight: 400;
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  src: url({{ static_url }}U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  src: url({{ static_url }}/some-path.ttf) format('truetype');
}
</style>
```

Further notes:
- wrapping the url inside double quotes doesn't help
- replacing `{{ variable }}` with a real value such as `https://something.at/some/path` prevents the problem

**Comment by revelt** [comment]
aha! ESP tags within CSS! I saw it coming, ESP within CSS is under-tested, I admit.

Sorry for the bug. That's definitely fixable, the most important is we have pinned the input/output.

I'll fix during these holidays, release patch today/tomorrow the latest.

**Comment by revelt** [comment]
Fixed. The Jinja/Nunjucks logic catches were completely absent in `@font-face` processing loop. I added not only `{{` but `{%` too. Releasing a patch this evening.

**Comment by revelt** [comment]
try email-comb@5.0.14
