### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by OctaneInteractive** [codsen/codsen#60]
**Package's name**
Which package from the monorepo is it for?

I'm using: string-strip-html, CJS version, 8.3.0

**Describe the bug**

After installation, I ran: `npm run dev` and got the following:

```
ERROR  Failed to compile with 1 errors                                                                                                                                                         09:32:40

error  in ../node_modules/string-strip-html/dist/string-strip-html.umd.js

Module parse failed: Unexpected token (18:133)
You may need an appropriate loader to handle this file type.
|  * @license MIT
|  * {@link https://codsen.com/os/ranges-sort/}
|  */const Ur={strictlyTwoElementsInRangeArrays:!1,progressFn:null};function $r(r,e){if(!Array.isArray(r)||!r.length)return r;const t={...Ur,...e};let a,n;if(t.strictlyTwoElementsInRangeArrays&&!r.filter((r=>r)).every(((r,e)=>2===r.length||(a=e,n=r.length,!1))))throw new TypeError(`ranges-sort: [THROW_ID_03] The first argument should be an array and must consist of arrays which are natural number indexes representing TWO string index ranges. However, ${a}th range (${JSON.stringify(r[a],null,4)}) has not two but ${n} elements!`);if(!r.filter((r=>r)).every(((r,e)=>!(!Number.isInteger(r[0])||r[0]<0||!Number.isInteger(r[1])||r[1]<0)||(a=e,!1))))throw new TypeError(`ranges-sort: [THROW_ID_04] The first argument should be an array and must consist of arrays which are natural number indexes representing string index ranges. However, ${a}th range (${JSON.stringify(r[a],null,4)}) does not consist of only natural numbers!`);const o=r.filter((r=>r)).length**2;let s=0;return Array.from(r).filter((r=>r)).sort(((r,e)=>(t.progressFn&&(s+=1,t.progressFn(Math.floor(100*s/o))),r[0]===e[0]?r[1]<e[1]?-1:r[1]>e[1]?1:0:r[0]<e[0]?-1:1)))}
| /**
|  * @name ranges-merge

 @ ../modules/utilities.js 3:22-50
 @ ./src/components/mixins/Utilities.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

Is this a readme file, or something?

**To Reproduce**

I get the same error each time I run: `npm run dev`.

**Expected behavior**
Vue should compile for development, and string-strip-html work.

**Additional context**

I'm running Vue.js 2.5.2, Node 14.7.0, and NPM 7.20.5

I'm using string-strip-html in: `../modules/utilities.js` accessible within Node, which is then referenced from: `./src/components/mixins/Utilities.js` allowing Vue to access the same resources without using the API.

Line 3 is: const { stripHtml } = require('string-strip-html')

I had been using 6.3.0 without problems.

**Comment by revelt** [comment]
Hi Wayne, sorry about the trouble. I'll do my best to release a new 8.3.1 patch soon, this night or next night — my plan is to build CJS using `esbuild` but with bundling enabled — same like our rehype/remark/eslint plugins.

Looking at your setup, theoretically, UMD should not be picked up, it's been originally aimed at consumption as script tag, directly from CDN's, to play around. In the meantime, try requiring the `/node_modules/string-strip-html/dist/string-strip-html.cjs.js` of v8.3.0 by path, directly somehow (try different frontal slash combinations, dot-slash etc, with/without extension etc).

**Comment by OctaneInteractive** [comment]
Hi Roy, much appreciated.

**Comment by revelt** [comment]
8.4.0 released, please try:

```
npm install string-strip-html@8.4.0
```

I'll close but feel free to reopen or open a new ticket.
