### ISSUE TITLE
[detergent] Add support for minus

### ISSUE THREAD

**Issue by ajitid** [codsen/codsen#62]
I recently discovered that [minus has its own unicode](https://youtu.be/YM2Nj691PMo?t=493) and I think it could be a good addition to the library.

![image](https://user-images.githubusercontent.com/26769888/209477824-a27b7973-a49f-48f1-a7f3-e09e84377fc2.png)

**Comment by revelt** [comment]
let's skip this, I haven't seen this being used anywhere
