### ISSUE TITLE
json-sort-cli@3.0.6 is missing lodash.isplainobject dependency

### ISSUE THREAD

**Issue by shouchechengadv** [codsen/codsen#63]
**Package's name**
json-sort-cli

**Describe the bug**
npx json-sort-cli "./sample.json"

throw `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'lodash.isplainobject' imported from C:\foo\npm\npm-cache\_npx\12b4b865febcf699\node_modules\json-sort-cli\cli.js` error

**To Reproduce**

1. no other npm global dependencies
2. npx json-sort-cli "./sample.json"
3. Ask `Need to install the following packages: json-sort-cli@3.0.6 Ok to proceed? `, enter `y`
5. See error

**Expected behavior**
run no error

**Screenshots**
![image](https://user-images.githubusercontent.com/87469760/210916587-9de73c8f-19a6-4a51-b6e9-cac52df40c22.png)

**Additional context**
Node.js v18.12.1
NPM v8.19.2

**Comment by revelt** [comment]
hi! Sorry about that, I already fixed it on my local, we just need to release.

**Comment by revelt** [comment]
fixed in `3.0.7` https://www.npmjs.com/package/json-sort-cli?activeTab=versions
