### ISSUE TITLE
Parsing problem when html exists in an attribute

### ISSUE THREAD

**Issue by ciscoheat** [codsen/codsen#65]
**Package's name**
string-strip-html

**Describe the bug**
I'm having trouble parsing html attributes when there are possibly malicious html inside them, for example:

```html
<a href="<span>ABC</span>">Test</a>
```

When parsing this, in `cb`, the `tag.attributes` is empty, and `proposedReturn` will keep part of the tag.

**To Reproduce**

```javascript
stripHtml('<a href="<span>ABC</span>">Test</a>', {
  cb: (event) => {
    if (event.tag.name == 'a' && !event.tag.slashPresent) console.log(event.tag.attributes);
    event.rangesArr.push(event.proposedReturn);
  }
})
```

Output is:
```
ABC\">Test
```

**Expected behavior**
That the content of the parsed `href` attribute should be present in `event.tag.attributes`, and that `event` contains correct information for completely stripping the tag.

Note: I've been using `skipHtmlDecoding: true`, but the problem also seems to exist when it is false.

**Comment by revelt** [comment]
`13.1.0` is out, please try! Thanks for raising it 👍
