### ISSUE TITLE
ignoreTagsWithTheirContents support for single closed tags

### ISSUE THREAD

**Issue by admc** [codsen/codsen#66]
**Package's name**
Which package from the monorepo is it for?
string-strip-html

**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

I would like ignoreTagsWithTheirContents to support the removal of a single tags like `<MyTag />,` but currently expects pairs like `<MyTag></MyTag>`. 

**Describe alternatives you've considered**
I would make that change to pairs to get it working, but this exists all over the place in a CMS so thats tons of work.

**Additional context**
Thank you so much for the awesome libraries!

**Comment by revelt** [comment]
hi Adam, certainly doable, I'll look into it.

**Comment by revelt** [comment]
13.2.0 has been just released, please try

**Comment by admc** [comment]
This works great, thank you so much!
