### ISSUE TITLE
Unable to resolve "string-strip-html"

### ISSUE THREAD

**Issue by cyril36** [codsen/codsen#69]
**Package's name**
    "string-strip-html": "^13.2.1"

**Describe the bug**
I have installed the package using yarn add string-strip-html
When launching the react-native app, i get the error Unable to resolve "string-strip-html"
My android simulator gives me the following error : 

```
However, this package itself specifies a `main` module field that could not be resolved node_modules/string-strip-html/index
None of these files exist:
  node_modules/string-strip-html/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)

```

I am using expo, i dont know if it can help

**To Reproduce**

1. install the package
2. execute react native app

**Expected behavior**
No error when executing the app
**Screenshots**
![image](https://user-images.githubusercontent.com/16116562/227949191-be4a5e5a-d933-4708-bc10-de8fbd02fd2f.png)
**Additional context**

Package installed 
```

"@apollo/client": "^3.7.9",
    "@react-navigation/native": "^6.1.4",
    "@react-navigation/native-stack": "^6.9.10",
    "@react-navigation/stack": "^6.3.16",
    "@react-spring/native": "^9.6.1",
    "expo": "~47.0.12",
    "expo-application": "~5.0.1",
    "expo-auth-session": "~3.8.0",
    "expo-calendar": "^11.1.1",
    "expo-dev-client": "~2.0.1",
    "expo-image-picker": "~14.0.2",
    "expo-location": "^15.1.1",
    "expo-random": "~13.0.0",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.2",
    "expo-web-browser": "~12.0.0",
    "html-to-draftjs": "^1.5.0",
    "lodash": "^4.17.21",
    "react": "18.1.0",
    "react-draft-wysiwyg": "^1.15.0",
    "react-hook-form": "^7.43.7",
    "react-native": "0.70.5",
    "react-native-apollo-devtools-client": "^1.0.4",
    "react-native-calendars": "^1.1294.0",
    "react-native-flipper": "^0.184.0",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-maps": "^1.4.0",
    "react-native-paper": "^5.4.0",
    "react-native-reanimated": "^3.0.2",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-vector-icons": "^9.2.0",
    "string-strip-html": "^13.2.1"
```

**Comment by revelt** [comment]
GH seems to be back, pls try again, reopen if issue persists

**Comment by cyril36** [comment]
Yes i am aware of GH failure but I have got this error 2 days ago

**Comment by revelt** [comment]
`13.2.1` is pure ESM, it doesn't have `main` field in the package.json (it has `exports` like all pure ESM packages do) — it seems your infra tooling doesn't support pure ESM packages — try the older version, [8.4.0](https://www.npmjs.com/package/string-strip-html/v/8.4.0) — it's been updated recently, I back-ported v13 to it, — it's non-pure ESM. Try.

**Comment by cyril36** [comment]
Apparently now it gets resolved , thank you
i dont know if there is a lot of different between version 8 and 13?
if you know how to fix it with version 13 , i would be curious to know how 

thank you for your help

**Comment by revelt** [comment]
So, you know there are two types, `require` and `import` you can use. In a nutshell, `require` was in the beginning, it is called CommonJS. Then `import` came, it's called ES Modules. But at the beginning, node couldn't run it natively, so we used to transpile it (via babel, rollup, [esm CLI](https://www.npmjs.com/package/esm) etc). Then, around node v.11, node maintainers added a feature flag to allow node to natively `import` and `export`, there was `require` no more. Since v12 you don't need a feature flag. You can read more at [Sindre Sorhus' page](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

The v13 is pure ESM, the v8 is the highest version being a non-pure ESM.
