### ISSUE TITLE
Not compatible with with Strapi

### ISSUE THREAD

**Issue by dinhkhanh** [codsen/codsen#70]
**Package's name**
string-strip-html

**Describe the bug**
`stripHtml` causes Strapi compilation error.
`string-strip-html` version: `^13.2.1`
Strapi FE version: 4.9.0 with Typescript

I've tried `string-strip-html` with Next.js and it works well.

**To Reproduce**

1. Use `string-strip-html` in Strapi (controller, services,..)
`import { stripHtml } from 'string-strpi-html'`

```
// /src/api/article/controller/article.ts

import { stripHtml } from 'string-strip-html';
import { factories } from '@strapi/strapi'


export default factories.createCoreController('api::article.article', ({ strapi }) => ({
  migrateCategories(ctx) {
    const myContent = stripHtml('<div>test</div>').result
    ctx.body = myContent
  }
}));
```

2. Run `yarn develop`
3. Terminal says 
```
Starting the compilation for TypeScript files in /strapi/project/path
error Command failed with exit code 1.
```

**Expected behavior**
Strapi compile and start normally.

**Comment by dinhkhanh** [comment]
I found the log by running `strapi ts:generate-types --verbose`

```
Starting the compilation for TypeScript files in /strapi/project/path
Error [ERR_REQUIRE_ESM]: require() of ES Module /strapi/project/path/node_modules/string-strip-html/dist/string-strip-html.esm.js from /strapi/project/path/dist/src/api/article/controllers/article.js not supported.
Instead change the require of string-strip-html.esm.js in /strapi/project/path/dist/src/api/article/controllers/article.js to a dynamic import() which is available in all CommonJS modules.
```

How to fix this?

**Comment by dinhkhanh** [comment]
Found the solution:
Install `string-strip-html` version 8.4.0 instead of 13.x

**Comment by revelt** [comment]
it seems `strapi` is not going to migrate to pure ESM for now, https://github.com/strapi/strapi/issues/9197 ¯\_(ツ)_/¯
