### ISSUE TITLE
string-strip-html removing whitespace unexpectedly

### ISSUE THREAD

**Issue by TomSwift** [codsen/codsen#71]
`string-strip-html`, version 8.4.0

I have some Markdown content that sometimes contains html tags, which I want to remove.   I thought `string-strip-html` would be perfect for this.

But `stripHtml()` is removing whitespace that has meaning in the markdown.   Can you confirm if this is expected, and why?  I'm not seeing an option to prevent this - am I overlooking something?

Input markdown - this example has NO html tags to strip, so I would expect the output to match the input:

```
    1. top level 1
       - sub list 1
       - sub list 2
          1. sub sub list 1
          1. sub sub list 2
             some text content some text content some text content some text content some text content
    
             > blockquote
    
             more text
          1. sub sub list 3
        - sub list 3
    2. top level 2
       * bullet 1
       * bullet 2
    3. top level 3
```

Output following stripHtml() with default opts:

```
    1. top level 1
    - sub list 1
    - sub list 2
    1. sub sub list 1
    1. sub sub list 2
    some text content some text content some text content some text content some text content
    
    > blockquote
    
    more text
    1. sub sub list 3
    - sub list 3
    2. top level 2
    * bullet 1
    * bullet 2
    3. top level 3
```

Note how all of the indent-spacing is gone.

**Comment by revelt** [comment]
Hi Nick, thank you for reaching out. The original intention was to strip HTML files, we don't "officially" support markdown, although I'm happy to do something about it.

If I added an option to ignore indentation, would that solve your problem?

**Comment by TomSwift** [comment]
Yeah I think so, thanks!   Maybe make it more generic "preserve whitespace" or something.

Maybe some clarity / refinement in your documentation if the intention is truly to work on HTML files proper.   I read 

> Strip HTML tags from strings. No parser, accepts mixed sources.

 and figured it was perfect for stripping HTML from my "mixed source" Markdown.

**Comment by revelt** [comment]
good point, I actually meant HTML + moustache or HTML + java, or any CRM templating languages out there sprinkled in HTML/CSS — but markdown at the end of the day is text, we just need to tackle peculiars

good point with documentation re markdown, I'll look into it as well

**Comment by revelt** [comment]
non-pure ESM `8.5.0` has been released; I'll close but don't hesitate to create a new issue if you see something; thank you for contributing
