### ISSUE TITLE
sortjson ci mode not using new line ending feature

### ISSUE THREAD

**Issue by dspaethe** [codsen/codsen#73]
**NPM Package**
json-sort-ci

**Command**
sortjson your_filename -ci

**Description**
The "ci" mode is not using the new EOL auto detect feature or react to the lineEnding Parameter. 
Files will be reported as "Unsorted files" because of deviating line endings.

**To Reproduce**
1. Have a json file with EOL = CRLF
2. Run the command: sortjson your_filename -ci

**Additional context**
This is related to your changes with Version 3,.1.0.
I Also added a comment in my PR: https://github.com/codsen/codsen/pull/72

**Comment by revelt** [comment]
hi David, thank you for spotting this, a fix is releasing currently
