### ISSUE TITLE
Vulnerable version of `lodash.trim` used in `string-strip-html`

### ISSUE THREAD

**Issue by philipp-tailor** [codsen/codsen#76]
**Package's name**
`string-strip-html`

**Describe the bug**
The dependency `lodash.trim` https://github.com/codsen/codsen/blob/abdcedbdbe77acb84cbb9a4f0df7a80b1c548f26/packages/string-strip-html/package.json#L80 is vulnerable to a ReDoS attack, see https://github.com/advisories/GHSA-29mw-wpgm-hmr9. It would be nice if a non-vulnerable version was used.

**Comment by revelt** [comment]
Hi Philipp, thank you for reporting, sorry about that, I'll bump asap. There will be few other goodies too in the next release.

**Comment by revelt** [comment]
Ok, I bumped and released `13.2.4` last night; I plan to back-port and release `8.5.0` as well, but that will be slightly later; I want to sort #78 and #71, too, as those back-tracked releases are a manual and tedious process.

Thanks again for raising this!
