### ISSUE TITLE
CommonJS module import issue

### ISSUE THREAD

**Issue by mbsanchez01** [codsen/codsen#77]
**Package's name**
Which package from the monorepo is it for?
is-language-code

**Describe the situation**
Description of what is happening.
I've imported this module on a typescript project, the code is like indicated in the homepage:

```
import { isLangCode, version } from "is-language-code";

const checkValidLanguage(langCode: string) =>  isLangCode(languageCode);

console.log(checkValidLanguage('fre'));
```

When I try to run this code I'm getting the next error:
> Instead change the require of is-language-code.esm.js to a dynamic import() which is available in all CommonJS modules.

**Comment by revelt** [comment]
the latest `is-language-code` is [pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), but if your setup is not there yet, try an older version, 3.1.0:

```
npm install is-language-code@3.1.0
```

**Comment by mbsanchez01** [comment]
Thank you @revelt version 3.1.0 worked, but why if I want to use a more recent version? should I need to set the typescript output to the module, it's the only way?

I've also tried using a dynamic import and it didn't work.
```
export async function isLanguageCode(str: string) {
  const module = await import('is-language-code');

  return isLangCode(str);
}
```

**Comment by revelt** [comment]
hm, if you want to import pure ESM inside CJS environment, the setup is different. See https://remix.run/docs/en/1.16.0/guides/mdx#advanced-configuration — or old Remix markdown configs, they go along the lines of:

```
const rehypeFigure = require("rehype-figure");
const remarkTypography = require("remark-typography");
const rehypeResponsiveTables = require("rehype-responsive-tables");

// can be an sync / async function or an object
exports.mdx = async (filename) => {
  const [
    rehypeHighlight,
    rehypeAutolinkHeadings,
    rehypeSlug,
    remarkGfm,
    remarkMdxFrontmatter,
    visit,
  ] = await Promise.all([
    import("rehype-highlight").then((mod) => mod.default),
    import("rehype-autolink-headings").then((mod) => mod.default),
    import("rehype-slug").then((mod) => mod.default),
    import("remark-gfm").then((mod) => mod.default),
    import("remark-mdx-frontmatter").then((mod) => mod.default),
    import("unist-util-visit").then((mod) => mod.visit),
  ]);

  return {
    remarkPlugins: [remarkGfm, remarkMdxFrontmatter, remarkTypography],
    rehypePlugins: [
      rehypeSlug,
      [
        rehypeAutolinkHeadings,
        {
          properties: {
            className: ["anchor"],
          },
          test: ["h2"],
        },
      ],
      [
        rehypeFigure,
        {
          className: "image-container",
        },
      ],
      rehypeHighlight,
      rehypeRelCodeBlockTitles,
      rehypeExternalLinks,
      rehypeAddClassToFrontMatterParagraph,
      [
        rehypeResponsiveTables,
        {
          up: ["Default", "Type", "Example", "Obligatory"],
        },
      ],
    ],
  };
};

exports.cacheDirectory = "./node_modules/.cache/remix";
```

notice they require CJS-ones, then set `exports.mdx` to be an awaited async function; then inside they `Promise.all` the `import`, grabbing either defaults `mod.default` or named exports like `mod.visit`, then they return a plain object.

Sorry for rough sketch. Try

The 4.1.2 fixed a memory leak — I'll try to backport that and release the `3.2.0` soon, don't worry about losing out on features.
