### ISSUE TITLE
Incorrect stripping results for text starting with words which are HTML tag names

### ISSUE THREAD

**Issue by michaldepta** [codsen/codsen#78]
**Package's name**
string-strip-html

**Describe the bug**
Passing a text that starts with any valid html tag name (e.g. 'head', 'title') and contains the '>' sign (plain or encoded as `&gt;`) produces unexpected results: everything before '>' is removed.

**To Reproduce**

1. Install `string-strip-html`
2. Call `stripHtml` with default options passing the following text: 'head > shoulders > knees > toes'
3. The result is 'shoulders > knees > toes'

**Expected behavior**
Only actual tags are removed. In the example above the result should be 'head > shoulders > knees > toes'.

**Screenshots**
![image](https://github.com/codsen/codsen/assets/11534413/5522dbb3-9c8f-42ac-ad1d-e99b163975c0)

**Additional context**
Also reproducible using non-pure ESM version 8.4.0. Same thing happens when the '>' sign is encoded: `head &gt; shoulders`

**Comment by revelt** [comment]
Hi Michał, sorry about that, I'll look into it

**Comment by revelt** [comment]
`13.3.0` in pure ESM has been released, but I still need to back-port it and release `8.5.0`; my plan is to tackle markdown indentations #71 as part of it, so I'll keep this issue open until `8.5.0` is out

**Comment by revelt** [comment]
non-pure ESM `8.5.0` has been released; I'll close but don't hesitate to create a new issue if you see something; thanks again for taking time to contribute

**Comment by michaldepta** [comment]
Thank you!
