### ISSUE TITLE
Type error prevents build

### ISSUE THREAD

**Issue by isfaaqATbazaks** [codsen/codsen#79]
**Package's name**
string-strip-html (v8.5.0)

**Describe the bug**
Build error in next because of type error

```
./node_modules/string-strip-html/types/index.d.ts:2:10
Type error: ',' expected.

  1 | type Range =
> 2 |   | [from: number, to: number]
    |          ^
  3 |   | [from: number, to: number, whatToInsert: string | null | undefined];
  4 | type Ranges = Range[] | null;
  5 | 
```

**To Reproduce**

1. Next TS project
2. add string-strip-html package
3. build

**Expected behavior**
builds successfully

**Screenshots**

**Comment by revelt** [comment]
Hi @isfaaqATbazaks sorry I can't recreate the issue, have a look at this test repo: https://github.com/revelt/strip-type-test — `ts-node` compiles the `8.5.0` fine — git clone it and run `npm run start`.

It's probably something misconfigured or outdated in your setup — try to recreate a minimal reproduction repository/sandbox and share here.

**Comment by revelt** [comment]
closing
