### ISSUE TITLE
deleteKey put key as value for undefined values

### ISSUE THREAD

**Issue by amirqasemi74** [codsen/codsen#8]
**Package's name**
object-delete-key

**Describe the bug**
this package put key as value in this code!!!

**To Reproduce**
```js
var {
	deleteKey
} = require("object-delete-key");
console.log(deleteKey({
	__typename: "sd",
	entryPoint: undefined,
}, {
	key: "__typename",
})) // {entryPoint: "entryPoint"}
```

**Expected behavior**
`{entryPoint: undefined}`

**Comment by revelt** [comment]
hi Amir, sorry for the bug. It's confirmed.

Normally I use this program to process content that comes from JSON, especially in context of email templating. The `undefined` was not accounted for, I admit, program does not explicitly state it's for JSON only... Thinking, it doesn't have to be, we _can_ catch that `undefined`.

My AST traversal programs like `ast-monkey`, operate on the following principle. If it stumbles upon a plain object, it gives you a `key` and `value`. If it stumbles upon an array, it only gives `key`. Further on, if value is `undefined`, it's interpreted as an array. Notice the const `current` in `ast-monkey-traverse` [Quick Take](https://codsen.com/os/ast-monkey-traverse/examples/#quick-take). But this paradigm only works on JSON-like AST, no `undefined` as values.

I'll do my best to fix it, probably over the weekend.

**Comment by revelt** [comment]
Fixed on my local; will appear in the next release.
