### ISSUE TITLE
email-comb uglifier crashes with `http://*` text

### ISSUE THREAD

**Issue by r0xorz** [codsen/codsen#83]
**Package's name**
`"email-comb": "^7.0.15"`

**Describe the bug**
`http://*` text or link (`<a href="http://*"></a>`) with an `uglify` turned on makes email-comb to crash.

**To Reproduce**

1. Go to https://codsen.com/os/email-comb/play
2. Paste this HTML
```
<html>

<body>
    <table>
        <tr>
            <td>
                http://*
            </td>
        </tr>
    </table>
    <table id="1">
        <tr>
            <td>
            </td>
        </tr>
    </table>
</body>

</html>
```
3. Turn on `Uglify`
4. See a `Codsen worker threw an error, and it should not have happened. It's a bug.` error

**Expected behavior**
No crash should happen.

**Additional context**
When a second table in the provided HTML is removed, or its `id` attribute is removed or emptied (`id=""`), no error appears.

**Comment by revelt** [comment]
Hi Giedrius, sorry about that, I'll fix.

**Comment by revelt** [comment]
please try [7.0.16](https://www.npmjs.com/package/email-comb/v/7.0.16) — the playground will follow soon

**Comment by r0xorz** [comment]
That was quick, thanks Roy, it works now! 😅
