### ISSUE TITLE
Removing brackets in password fields

### ISSUE THREAD

**Issue by dbclkh** [codsen/codsen#86]
**Package's name**
string-strip-html - stripHtml

**Describe the bug**
We submit a JSON object to our API, it contains fields with html that needs to be striped and fields with password that can contain < & >.
The password field can be "something<345!" and should not be striped, but it ends up with "something". The <345! is removed.

**To Reproduce**
The json: `{"htmlfield":"<script>let evilscript = '';</script>","passwordfield":"something<345!"}`

**Expected behavior**
The htmlfield should be striped from the evil script tag and the passwordfield should be kept as is.

**Additional context**
We are using your example with parsing a JSON string and the latest version.

**Comment by revelt** [comment]
hi Lars, sorry about that. Would it work if you set to strip only recognised HTML? `opts.stripRecognisedHTMLOnly` setting?

**Comment by dbclkh** [comment]
Hi - that did the trick 😄 

Can you please update your "QuickTake" https://codsen.com/os/string-strip-html#quick-take regarding the "// detects raw, legit brackets:"...

Thank you very much for the quick help! 👍

**Comment by revelt** [comment]
great! algorithm does try to detect legit ones, but mainly spaced-out brackets, if you check unit tests we cover quite a lot of cases, it just leans on the aggressive side, the `opts.stripRecognisedHTMLOnly` turns it less aggressive
