### ISSUE TITLE
edit-package-json nesting issue

### ISSUE THREAD

**Issue by forivall** [codsen/codsen#89]
**Package's name**
Which package from the monorepo is it for? edit-package-json

**Describe the bug**

With the following json object: `{"b": [{"a": [],"o": {}},{"yz": "0"}]}`, editing the `yz` value does not work.

**To Reproduce**

1. See my repro branch on my fork; i've created fixtures. https://github.com/codsen/codsen/compare/main...forivall:codsen:repro-editpackagejson-bug

changing the object at `b.0` allows the modification to occur, seems to be an issue with how the object path tracking works.

**Expected behavior**

The value should be able to be modified.

```js
import * as editJson from 'edit-package-json';

editJson.set('{"b": [{"a": [],"o": {}},{"yz": "0"}]}', "b.1.yz", "1"')
// result should be `{"b": [{"a": [],"o": {}},{"yz": "1"}]}`
```

**Screenshots**

**Additional context**

**Comment by revelt** [comment]
Hi Emily, sorry about that, I'll look into this.

**Comment by revelt** [comment]
Hi Emily, [0.8.18](https://www.npmjs.com/package/edit-package-json/v/0.8.18) has just been released, please try.
