### ISSUE TITLE
string-strip-html error when deploy cloud functions

### ISSUE THREAD

**Issue by ThanhNguyen140797** [codsen/codsen#9]
**Package's name**
string-strip-html

**Describe the bug**
I'm using string-strip-html in cloud functions, when i deploy functions, i got this error:

node_modules/ranges-push/types/index.d.ts:1:27 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];
                          
node_modules/ranges-push/types/index.d.ts:1:39 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];

node_modules/ranges-push/types/index.d.ts:1:56 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];

node_modules/ranges-push/types/index.d.ts:1:68 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];

node_modules/ranges-push/types/index.d.ts:1:90 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];

node_modules/string-strip-html/types/index.d.ts:3:27 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];

node_modules/string-strip-html/types/index.d.ts:3:39 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];

node_modules/string-strip-html/types/index.d.ts:3:56 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];

node_modules/string-strip-html/types/index.d.ts:3:68 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];
                                                              
node_modules/string-strip-html/types/index.d.ts:3:90 - error TS1005: ',' expected.
declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];

**Comment by revelt** [comment]
hi! Sorry for the bug. What does `tsc --version` say in the cloud environment? This [post](https://stackoverflow.com/questions/46398916/typescript-error-ts1005-expected-ii/51936515) implies TS1005 might be about older TS versions. I've got the `typescript` [dependency](https://github.com/codsen/codsen/blob/main/packages/string-strip-html/package.json#L140) set to `4.2.3`, that's what Rollup would use to generate the type definitions.

**Comment by ThanhNguyen140797** [comment]
Hi, my current typescript version is 3.8.0. Upgrade to 4.2.3 fix this error.
Thank you so much.

**Comment by joelstevick** [comment]
Hi!


Great function!  I use it with my Angular app.

However, for my Google cloud function I am using TS 4.5.5 and I am getting the same error.

Any advice?

Thanks!
Joel
